### ISSUE TITLE
Add configurable GITHUB_ROOT 

### ISSUE THREAD

**Issue by jessicaxiejw** [burke/minidev#12]
@burke I have a PR for configurable `GITHUB_ROOT`, but I am not allowed to create pull request. Could you give me the permission?

**Comment by ajkerr** [comment]
@jessicaxiejw You can fork this repository and create a pull request in your fork against this upstream repository. For example, see #13.

**Comment by jessicaxiejw** [comment]
Uh I see, it works now: https://github.com/burke/minidev/pull/15

@ajkerr Thank you so much! I actually have never contributed to an open source project. This is my first time. Thanks for the help.
